### ISSUE TITLE
Safe Links in Teams

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#123]
I wanted to check for this "Safe Links in Teams" feature that seems listed here https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans but I do not see it. Is it possible that it is not yet implemented? https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=In%20development&searchterms=safe%2Clinks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@javirivas80 Thank you for your feedback. We've corrected the service description.

**Comment by jhuylebroeck** [comment]
I think it still incorrectly states "no" in the table under "Feature availability across Advanced Threat Protection (ATP) plans"
